export {default as Hero} from './Hero/Hero';
export {default as SeoSection} from './SeoSection/SeoSection';
export {default as SeoServices} from './SeoServices/SeoServices';
export {default as SectionalHeading} from './SectionalHeading/SectionalHeading';
export {default as StatSection} from './StatsSection/StatSection';
export {default as FactSlider} from './FactSlider/FactSlider';
export {default as ExperienceSec} from './ExperienceSec/ExperienceSec';
export {default as Testimonial} from './Testimonial/Testimonial';
export {default as Certification} from './Certification/Certification';
export {default as SeoServiceSilder} from './SeoServiceSilder/SeoServiceSilder';
export {default as SubmitGoogle} from './SubmitGoogle/SubmitGoogle'